namespace Irc.Models.Enumerations;

public enum EnumJoinResult
{
    ERR_NEEDMOREPARAMS,
    ERR_BANNEDFROMCHAN,
    ERR_INVITEONLYCHAN,
    ERR_BADCHANNELKEY,
    ERR_CHANNELISFULL,
    ERR_BADCHANMASK,
    ERR_NOSUCHCHANNEL,
    ERR_TOOMANYCHANNELS,
    ERR_ALREADYINCHANNEL,
    ERR_NICKINUSE,
    RPL_TOPIC
}